config/routes.rb
Rails.application.routes.draw do

  root to:'sessions#new'
  get 'home', to: "questions#home"

  resources :users, only: [:new, :create] do
    resources :tickets, except: [:edit, :update, :destroy]
    resources :questions do
      resources :comments, except: [:index, :show]
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  validates :questions, :title, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  validate :post_limit, :on => :create
  validates :topic, :effective, :prepare, :practice, :info, presence: true

  scope :today, -> { where(:created_at => (Time.now.beginning_of_day..Time.now.end_of_day))}

  def post_limit
    if user.tickets.today.count >= 1
      errors.add(:post, "limit once a day")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :questions
  has_many :comments
  has_many :tickets

  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /@/, message: "must have format abc@abc.com"
  validates :password, length: { minimum: 4, message: "minimum 4 characters long" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?
  helper_method :is_admin?
  helper_method :admin_only

  def current_user
    @c_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def check_user
    unless logged_in?
      flash[:notice] = "Please login first!"
      redirect_to root_path
    end
  end

  def is_admin?
    true if session[:user_email] === "admin@gmail.com"
  end

  def admin_only
    unless is_admin?
      flash[:notice] = "For admins only!"
      redirect_to home_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :your_comment?, except: [:new, :create]

  def new
    @qns = Question.find(params[:question_id])
    @comment = Comment.new
    @prev_comments = Comment.where(question_id: params[:question_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.question_id = params[:question_id].to_i
    @comment.user_id = params[:user_id].to_i

    if @comment.save
      redirect_to user_question_path(current_user, @comment.question_id), notice: "Comment saved!"
    else
      render "new", notice: "Creation failed. Please contact administrator."
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @qns = Question.find(params[:question_id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(comment_params)
      redirect_to user_question_path(current_user, @comment.question_id), notice: "Comment updated!"
    else
      render "edit", notice: "Edit failed. Please contact administrator."
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to user_question_path(current_user, params[:question_id]), notice: "Comment deleted!"
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :comments)
  end

  def your_comment?
    @comment = Comment.find(params[:id])
    redirect_to user_question_path(current_user, params[:question_id]), notice: "That does not belong to you!" unless @comment.user == current_user
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :check_user, except: [:home]
  before_action :your_question?, only: [:edit, :update, :destroy]

  def home
    @home = Question.all.order(updated_at: :desc)
  end

  def index
    @myqns = Question.where(user_id: current_user).order(updated_at: :desc)
  end

  def show
    @qns = Question.find(params[:id])
    @comment = Comment.where(question_id: params[:id]).order(updated_at: :desc)
  end

  def new
    @qns = Question.new
  end

  def create
    @qns = Question.new(question_params)
    @qns.user = current_user

    if @qns.save
      redirect_to home_path, notice: "Successfully created!"
    else
      render "new", notice: "Couldn't create question. Please contact administrator."
    end
  end

  def edit
    @qns = Question.find(params[:id])
  end

  def update
    @qns = Question.find(params[:id])

    if @qns.update_attributes(question_params)
      redirect_to user_question_path(current_user, @qns), notice: "Successfully updated!"
    else
      render "edit", notice: "Update failed"
    end
  end

  def destroy
    qns = Question.find(params[:id])
    qns.destroy
    redirect_to home_path, notice: "successfully deleted!"
  end

  private

  def question_params
    params.require(:question).permit(:title, :questions)
  end

  def your_question?
    @qns = Question.find(params[:id])
    redirect_to home_path, notice: "This does not belong to you!" unless @qns.user == current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:user_email] = user.email
      redirect_to home_path, notice: "Welcome, #{user.email}"
    else
      render "new", notice: "Invalid login details"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "logged out"
    redirect_to root_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :admin_only, only: [:index]

  def index
    @ticket = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user

    if @ticket.save
      redirect_to home_path, notice: "Your ticket was saved!"
    else
      render "new", notice: "Ticket was not saved. Please contact administrator."
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:topic, :effective, :prepare, :practice, :info, :other)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "Successfully created! Please login"
    else
      render "new", notice: "Signing up failed. Please contact administrator"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= simple_form_for [current_user, @qns, @comment] do |f| %>
  <%= f.input :title %>
  <%= f.input :comments %>
  <%= f.button :submit %>
<% end %>

app/views/comments/new.html.erb
<!-- displaying the question -->
<h1>Question ID: <%= @qns.id %></h1>
<h3>Title: <%= @qns.title %></h3>
<p><%= @qns.questions %></p>
<p>Updated at: <%= @qns.updated_at %></p>
<p>Posted by: <%= @qns.user.email %></p>
<hr>

<!-- form for adding comments -->
<h1>Add your comment</h1>
<%= simple_form_for [current_user, @qns, @comment] do |f| %>
  <%= f.input :title %>
  <%= f.input :comments %>
  <%= f.button :submit %>
<% end %>
<hr>

<!-- displaying all comments -->
<% if @prev_comments.present? %>
<h3>Comments for this post</h3>
  <% @prev_comments.each do |c| %>
  <h3>Title: <%= c.title %></h3>
  <p><%= c.comments %></p>
  <p>Updated at: <%= c.updated_at %></p>
  <p>Posted by: <%= c.user.email %></p>
  <hr>
  <% end %>
<% end %>

<%= link_to "Back", user_question_path(current_user, @qns) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.present? %>
      <% if notice.present? %>
        <h1><%= notice %></h1>
      <% else %>
    <h1>Welcome, <%= session[:user_email] %></h1>
      <% end %>
    <%= link_to "Sign Out", session_path(current_user), method: :delete, data: { confirmation: "Are You Sure?" } %>
    <%= link_to "My Posts", user_questions_path(current_user) %>
    <%= link_to "Exit Ticket", new_user_ticket_path(current_user) %>
    <% if is_admin? %>
    <%= link_to "All Tickets", user_tickets_path(current_user) %>
    <% end %>
    <hr>
    <% else %>
    <h1>Welcome</h1>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit This Question</h1>

<%= simple_form_for [current_user, @qns] do |q| %>
  <%= q.input :title %>
  <%= q.input :questions %> <br>
  <%= q.button :submit %>
<% end %>

app/views/questions/home.html.erb
<!-- show all questions  -->
<% @home.each do |q| %>
<h3> Title: <%= q.title %></h3>
<p> Question: <br><%= q.questions %></p> <br>
<%= q.created_at %> <br>
<p>Posted by: <%= q.user.email %></p>
<%= link_to "Show", user_question_path(q.user_id, q) %>
<hr>
<% end %>

<br>
<br>

<%= link_to "Create New Questions", new_user_question_path(current_user) %>

app/views/questions/index.html.erb
<!-- show all questions belonging to user -->
<h3>My Posts</h3>

<% @myqns.each do |q| %>
  <h3> Title: <%= q.title %></h3>
  <p> Question: <br><%= q.questions %></p> <br>
  <%= q.created_at %> <br>
  <%= link_to "Show", user_question_path(q.user_id, q) %>
  <%= link_to "Edit", edit_user_question_path(current_user, q) %>
  <%= link_to "Delete", user_question_path(current_user, q), method: :delete, data: { confirm: "Are You Sure?" } %>
  <hr>
<% end %>
<br>
<%= link_to "Back", home_path %>

app/views/questions/new.html.erb
<h1>New Questions</h1>

<%= simple_form_for [current_user, @qns] do |q| %>
  <%= q.input :title %>
  <%= q.input :questions %>
  <%= q.button :submit %>
<% end %>

<hr>

<%= link_to "Back", home_path %>

app/views/questions/show.html.erb
<!-- display current question -->
<h1>Question: <%= @qns.id %></h1>
<h3>Title: <%= @qns.title %></h3>
<p><%= @qns.questions %></p>
<p>Updated at: <%= @qns.updated_at %></p>
<p>Posted by: <%= @qns.user.email %></p>
<% if current_user == @qns.user %>
<%= link_to "Edit Question", edit_user_question_path(current_user, @qns) %>
<% end %>
<hr>

<!-- display all comments for this question -->
<% if @comment.present? %>
  <h3>COMMENTS</h3>
  <% @comment.each do |c| %>
  <h3>Title: <%= c.title %></h3>
  <p><%= c.comments %></p>
  <p>Updated at: <%= c.updated_at %></p>
  <p>Posted by: <%= c.user.email %></p>
  <%= link_to "Edit Comments", edit_user_question_comment_path(current_user, @qns, c) %>
  <%= link_to "Delete", user_question_comment_path(current_user, @qns, c), method: :delete, data: { confirm: "Are You Sure?" } %>
<hr>
  <% end %>
<% end %>

<!-- additional links -->
<%= link_to "Add Comments", new_user_question_comment_path(current_user, @qns) %> <br> <br>
<%= link_to "Home", home_path %>

app/views/tickets/index.html.erb
<h1>List of Exit Tickets</h1>

<% @ticket.each do |t| %>
  <p>Topic</p><%= t.topic %> <br>
  <p>My instructional team was effective in helping me achieve the learning objectives for this lesson</p><%= t.effective %> <br>
  <p>The lesson agenda was well-organized and sufficient time was given for each activity. </p><%= t.prepare %> <br>
  <p>I feel prepared to continue practicing this skill outside of class.</p><%= t.practice %> <br>
  <p>(Optional) Would you like to elaborate on questions above?</p><%= t.info %> <br>
  <p>What is the most valuable piece of information you learned during today’s lesson?</p><%= t.other %>
  <br>
  <br>
  <p>Submitted by: <%= t.user.email %></p>
  <hr>
<% end %>

app/views/tickets/new.html.erb
<h1>Exit Ticket</h1>
<%= @ticket.errors.full_messages if @ticket.errors.full_messages.present? %>

<%= simple_form_for [current_user, @ticket] do |f| %>
  <%= f.input :topic %>
  <br><p>My instructional team was effective in helping me achieve the learning objectives for this lesson</p>
  <%= f.input :effective, label: "Effectiveness", collection: 1..10, as: :radio_buttons %>
  <br><p>The lesson agenda was well-organized and sufficient time was given for each activity. </p>
  <%= f.input :prepare, collection: 1..10, as: :radio_buttons %>
  <br><p>I feel prepared to continue practicing this skill outside of class.</p>
  <%= f.input :practice, collection: 1..10, as: :radio_buttons%>
  <br><p>What is the most valuable piece of information you learned during today’s lesson?</p>
  <%= f.input :info %>
  <br><p>(Optional) Would you like to elaborate on questions above?</p>
  <%= f.input :other %>
  <%= f.button :submit %>
<% end %>

app/views/tickets/show.html.erb
<h1>Tickets#show</h1>
<p>Find me in app/views/tickets/show.html.erb</p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.full_messages %>
  <% else %>
    <h1>Welcome</h1>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :email %>  <br>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %> <br>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %> <br>
  <%= f.password_field :password_confirmation %>
  <br>
  <br>
  <%= f.submit "Sign Up" %>
<% end %>